import JSZip from 'jszip';
import { kml } from '@tmcw/togeojson';

/**
 * Parses a .kmz or .kml File object into a GeoJSON FeatureCollection.
 * Extracts styles (stroke, fill) generated by Google My Maps.
 * @param {File} file - The .kmz or .kml file.
 * @returns {Promise<Object>} Object containing { geojson, bounds }.
 */
export async function parseKMZ(file) {
  try {
    let kmlText = '';

    if (file.name.toLowerCase().endsWith('.kmz')) {
      const zip = new JSZip();
      const zipContent = await zip.loadAsync(file);

      // Find the first .kml file inside the KMZ archive (usually doc.kml)
      const kmlFileName = Object.keys(zipContent.files).find(fileName =>
        fileName.toLowerCase().endsWith('.kml')
      );

      if (!kmlFileName) {
        throw new Error('Tidak ditemukan file .kml di dalam archive .kmz ini.');
      }

      kmlText = await zipContent.files[kmlFileName].async('text');
    } else if (file.name.toLowerCase().endsWith('.kml')) {
      kmlText = await file.text();
    } else {
      throw new Error('Format file tidak didukung. Harap unggah file .kmz atau .kml');
    }

    // DEBUG: log raw KML text (first 2000 chars)
    console.log('[KMZ Parser] Raw KML (first 2000 chars):', kmlText.substring(0, 2000));

    const parser = new DOMParser();
    const kmlDom = parser.parseFromString(kmlText, 'text/xml');
    
    // Check for parse errors
    const parseError = kmlDom.getElementsByTagName('parsererror');
    if (parseError.length > 0) {
      throw new Error('Gagal melakukan parsing file KML.');
    }

    // Convert to GeoJSON using @tmcw/togeojson
    const geoJson = kml(kmlDom);

    // DEBUG: log full GeoJSON
    console.log('[KMZ Parser] Raw GeoJSON from togeojson:', JSON.stringify(geoJson, null, 2));
    console.log('[KMZ Parser] Feature count:', geoJson?.features?.length || 0);

    if (!geoJson || !geoJson.features || geoJson.features.length === 0) {
      throw new Error('File KMZ tidak berisi data geometri yang valid.');
    }

    // Track bounds for auto-zoom
    let minLng = Infinity, maxLng = -Infinity;
    let minLat = Infinity, maxLat = -Infinity;

    const updateBounds = (lng, lat) => {
      if (lng < minLng) minLng = lng;
      if (lng > maxLng) maxLng = lng;
      if (lat < minLat) minLat = lat;
      if (lat > maxLat) maxLat = lat;
    };

    // Recursively traverse coordinates to compute bounds
    const traverseCoords = (coords) => {
      if (!Array.isArray(coords)) return;
      if (typeof coords[0] === 'number' && typeof coords[1] === 'number') {
        updateBounds(coords[0], coords[1]);
        return;
      }
      coords.forEach(c => traverseCoords(c));
    };

    // Normalize GeoJSON features with fallback styles and compute bounds
    geoJson.features = geoJson.features.map((feature, idx) => {
      if (!feature.properties) feature.properties = {};

      // Log each feature for debugging
      console.log(`[KMZ Parser] Feature ${idx}:`, {
        type: feature.geometry?.type,
        coordsLength: feature.geometry?.coordinates?.length,
        props: { ...feature.properties }
      });

      // Compute bounds from geometry
      if (feature.geometry && feature.geometry.coordinates) {
        traverseCoords(feature.geometry.coordinates);
      }

      // --- STYLE NORMALIZATION ---
      // Google My Maps sometimes puts color in non-standard props
      // @tmcw/togeojson extracts styles into stroke, stroke-width, stroke-opacity, fill, fill-opacity
      
      // Ensure stroke color
      feature.properties.stroke = feature.properties.stroke || '#EB1D24';
      
      // Ensure stroke width is a number
      const sw = parseFloat(feature.properties['stroke-width']);
      feature.properties['stroke-width'] = isNaN(sw) ? 4 : Math.max(sw, 1);
      
      // Ensure stroke opacity is a number
      const so = parseFloat(feature.properties['stroke-opacity']);
      feature.properties['stroke-opacity'] = isNaN(so) ? 1.0 : so;
      
      // Ensure fill color
      feature.properties.fill = feature.properties.fill || feature.properties.stroke || '#EB1D24';
      
      // Ensure fill opacity is a number
      const fo = parseFloat(feature.properties['fill-opacity']);
      feature.properties['fill-opacity'] = isNaN(fo) ? 0.35 : fo;
      
      // Ensure name exists
      feature.properties.name = feature.properties.name || `KMZ Feature ${idx + 1}`;

      return feature;
    });

    const bounds = (minLng !== Infinity) 
      ? [[minLng, minLat], [maxLng, maxLat]] 
      : null;

    console.log('[KMZ Parser] Computed bounds:', bounds);
    console.log('[KMZ Parser] Feature types:', geoJson.features.map(f => f.geometry?.type));
    console.log('[KMZ Parser] Final GeoJSON:', JSON.stringify(geoJson, null, 2).substring(0, 3000));

    return { geojson: geoJson, bounds };
  } catch (err) {
    console.error('[KMZ Parser] Error:', err);
    throw err;
  }
}
